server.port: 8888
security.basic.enable: false
management.security.enabled: false

spring:
   application:
     name: configserver
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: file:///c:/code/spring-cloud-introduction/config-yml